repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    exclude: ^.*\.md$
  - id: end-of-file-fixer
  - id: debug-statements
  - id: no-commit-to-branch
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: detect-private-key
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: check-merge-conflict

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
    exclude: ^(.*).lock$
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint

- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
    types: [python]

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    additional_dependencies: ['.[pyproject]']

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    name: black-code-formatter
    additional_dependencies: ['.[pyproject]']

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [--in-place, --remove-all-unused-imports, --remove-unused-variable]

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    files: ^jumpradius_updater/
    additional_dependencies: [flake8-print, flake8-docstrings, '.[flake8]']
    types: [python]

- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.5
  hooks:
  - id: python-bandit-vulnerability-check
